##Red-Wine Quality Project

###Classification

##Data Preprocessing

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
dataset = pd.read_csv('/content/datasets_4458_8204_winequality-red.csv')

In [36]:
dataset

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [37]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [38]:
dataset['quality'].unique()

array([5, 6, 7, 4, 8, 3])

##Separate Features & Target

* 'Quality' is the target

* Others details or columns are features

In [39]:
X = dataset.iloc[: ,:-1].values
y = dataset.iloc[:, -1].values

##Splitting Data Into Train & Test Sets

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size=0.2)

##Standardization

In [42]:
from sklearn.preprocessing import StandardScaler

In [43]:
sc = StandardScaler()

In [44]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

##Train on Different Algorithms

* Here I've trained in 5 different algorithms

1. LogisticRegression  -  'linear_model'  library used

2. KNeighborsClassifier  - 'neighbors'  library used

3. DecisionTreeClassifier  - 'tree'  library used

4. RandomForestClassifier  - 'ensemble'  library used

5. SVC  - 'svm' library used

In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [46]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [47]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [48]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

In [49]:
from sklearn.metrics import confusion_matrix

In [50]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [51]:
l_c

array([[ 0,  1,  2,  0,  0,  0],
       [ 0,  0,  3,  5,  0,  0],
       [ 0,  0, 97, 37,  1,  0],
       [ 0,  2, 49, 77,  1,  0],
       [ 0,  0,  2, 23, 13,  0],
       [ 0,  0,  0,  4,  3,  0]])

In [52]:
k_c

array([[ 0,  0,  3,  0,  0,  0],
       [ 0,  0,  5,  3,  0,  0],
       [ 0,  3, 97, 32,  3,  0],
       [ 0,  1, 45, 71, 12,  0],
       [ 0,  0,  3, 23, 12,  0],
       [ 0,  0,  1,  3,  3,  0]])

In [53]:
d_c

array([[ 0,  1,  1,  0,  1,  0],
       [ 1,  0,  5,  2,  0,  0],
       [ 0,  3, 93, 32,  7,  0],
       [ 0,  2, 25, 90, 11,  1],
       [ 0,  1,  2,  9, 25,  1],
       [ 0,  0,  2,  2,  2,  1]])

In [54]:
r_c

array([[  0,   0,   3,   0,   0,   0],
       [  0,   0,   6,   2,   0,   0],
       [  0,   0, 102,  30,   3,   0],
       [  0,   0,  27,  98,   4,   0],
       [  0,   0,   1,  14,  23,   0],
       [  0,   0,   0,   4,   2,   1]])

In [55]:
s_c

array([[ 0,  0,  3,  0,  0,  0],
       [ 0,  0,  4,  4,  0,  0],
       [ 0,  0, 98, 37,  0,  0],
       [ 0,  0, 52, 77,  0,  0],
       [ 0,  0,  2, 36,  0,  0],
       [ 0,  0,  0,  7,  0,  0]])

In [56]:
ks_c

array([[  0,   0,   3,   0,   0,   0],
       [  0,   0,   5,   3,   0,   0],
       [  0,   0, 106,  27,   2,   0],
       [  0,   0,  52,  72,   5,   0],
       [  0,   0,   2,  26,  10,   0],
       [  0,   0,   0,   5,   2,   0]])

##Result

In [57]:
from sklearn.metrics import accuracy_score

In [58]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [59]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.584375
KNN: 0.5625
Decision Tree: 0.653125
Random Forest: 0.7
Linear SVC: 0.546875
Kernel SVC: 0.584375


##Conclusion

According to this classification, the 'RandomForestClassifier' is giving the better efficiency. 

So we can consider this as the best algorithms for this dataset using classification as 'RandomForestClassifier'.